name: run-tests

on:
  push:
  pull_request:

jobs:
  run-tests:

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true

      - name: Initialize conda for shell interaction
        run: |
          conda init

      - name: Reload the shell
        run: source /home/runner/.bashrc

      - name: Create conda environment and install dependencies
        run: |
          conda env create -f environment.yml
          conda init
          conda activate forest_health_project-env

      - name: Install pip
        run: conda install pip

      - name: Install project package from pyproject.toml
        run: |
          pip install .

      - name: Run tests
        run: |
          conda activate forest_health_project-env
          pytest
